import Head from "next/head";
import { useState, createContext, useContext } from "react";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import Student from "../components/Student";
import styles from "../styles/Home.module.css";
import themes from "../styles/theme";

// outside of the component
const themeContext = createContext({});

export function useTheme() {
  return useContext(themeContext);
}

export default function Home() {
  const [theme, setTheme] = useState("light");
  const colors = themes[theme];

  function toggleTheme() {
    if (theme === "light") {
      setTheme("dark");
    } else {
      setTheme("light");
    }
  }

  const students = [
    { id: 1, name: "Karin", specialty: "Travelling" },
    { id: 2, name: "Rohan", specialty: "Cycling" },
    { id: 3, name: "Koen", specialty: "Gaming" },
  ];

  return (
    <themeContext.Provider
      value={{ colors: colors, theme: theme, toggleTheme: toggleTheme }}
    >
      <div
        className={styles.container}
        style={{ backgroundColor: colors.backgroundColor }}
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navigation colors={colors} />

        <main
          className={styles.main}
          style={{ backgroundColor: colors.backgroundColor }}
        >
          {students.map((student) => {
            return (
              <Student
                key={student.id}
                name={student.name}
                specialty={student.specialty}
                colors={colors}
              />
            );
          })}
        </main>
        <Footer colors={colors} />
      </div>
    </themeContext.Provider>
  );
}
