import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import themes from "../styles/theme";

export default function Home() {
  const [theme, setTheme] = useState("light");
  const colors = themes[theme];

  function toggleTheme() {
    if (theme === "light") {
      setTheme("dark");
    } else {
      setTheme("light");
    }
  }

  return (
    <div
      className={styles.container}
      style={{ backgroundColor: colors.backgroundColor }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <button onClick={toggleTheme}>{theme === "light" ? "🌚" : "🌞"}</button>
      </nav>
      <main
        className={styles.main}
        style={{ backgroundColor: colors.backgroundColor }}
      ></main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
